# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c03673dcc4431b7e44cf068fcffee1cabe3fb00a65ee0bcc3efd2605d63c362e988a44a574424cc46fe45d69726424aa931194ca54e948955b46f94b291b2a62

test:
  secret_key_base: 87e2ce8b18ccb0410ccfbeb1a30e7837ae7144948d480634aa2547af5ae2adfe4ee062b491c033d9198f05d714903e2f0ffb1f32e5983ad1d5ffad1828a75084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
